### PR TITLE
[#127] Fix doctest for text-1.2.3

### LINKED ISSUE #127: Doctest failure for universum-1.0.4
As seen on the Stackage build server:

```
> /tmp/stackage-build12/universum-1.0.4$ dist/build/universum-doctest/universum-doctest
### Failure in src/Universum/String/Conversion.hs:78: expression `decodeUtf8 @Text @ByteString "\208\208\176\209\130\208\176\208\186"'
expected: "\65533\65533\1090\1072\1082"
 but got: "\65533\1072\1090\1072\1082"
Examples: 112  Tried: 111  Errors: 0  Failures: 1
```

### PR DESCRIPTION
**Pull request by ChShersh**
Resolves #127

### CODE REVIEW

File: src/Universum/String/Conversion.hs [hunk 1]
```diff
@@ -73,12 +74,21 @@ class ConvertUtf8 a b where
...
+    --
+    -- >>> decodeUtf8 @Text @ByteString "\208\208\176\209\130\208\176\208\186"
+    -- "\65533\1072\1090\1072\1082"
+    -- >>> decodeUtf8Strict @Text @ByteString "\208\208\176\209\130\208\176\208\186"
+    -- Left Cannot decode byte '\xd0': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
+#else
     -- | Decode as utf8 string but returning execption if byte sequence is malformed.
     --
     -- >>> decodeUtf8 @Text @ByteString "\208\208\176\209\130\208\176\208\186"
     -- "\65533\65533\1090\1072\1082"
```
Comment (vrom911) [inline src/Universum/String/Conversion.hs]: Probably it's better to reduce some duplication and to put `if` only on this line. I guess it won't spoil readability, what do you think?

Comment (ChShersh) [reply src/Universum/String/Conversion.hs]: @vrom911 You're right, this would be better. But I didn't manage to make it work... For some unknown reason if I put `#if` only for this single line tests doesn't work as expected. Probably `-XCPP` doesn't work well with comments 🙁 I didn't spend much time investigating this. Probably, if we use better CPP-preprocessor (like `cpphs`) we can avoid this problem. But I'm not sure I want to add `cpphs` to dependencies right now...

Comment (ChShersh) [reply src/Universum/String/Conversion.hs]: I can try to do that

Comment (ChShersh) [reply src/Universum/String/Conversion.hs]: @vrom911 I tried. If I put only those two lines under `#if` then doctest just ignores both test. I think it doesn't like empty lines in the middle of documentation... I guessed that the reason why it worked for `o-clock` is in the fact that `o-clock` uses block comments `{- | -}`. If I replace with block comments then everything works!

Comment (vrom911) [reply src/Universum/String/Conversion.hs]: Oh! I see now..
