### PR TITLE
[#130] Merge 'ToList' and 'Container', [#118] Export 'Type'

### LINKED ISSUE #60: Numeric.Natural
Re-export it from `base`.

### LINKED ISSUE #118: Improve GHC 8.2.2 support
I've discovered magic spell in `Universum.Base` module:

* https://github.com/serokell/universum/blob/d14925085b1fc7037f25542618b931d22dcf13b4/src/Universum/Base.hs#L104

We should research on this and discover whether it useful or not.

### LINKED ISSUE #130: Merge 'ToList' and 'Container' into single type class 'Container'
I don't see point in having both `ToList` and `Container`. Maybe @neongreen can clarify. But I think second type class is redundant.

### LINKED ISSUE #144: Add 'Exc' pattern synonym
Introduced by @int-index 

Implementation:

```haskell
pattern Exc :: Exception e => e -> SomeException
pattern Exc e <- (E.fromException -> Just e)
```

So instead of writing something like this:

```haskell
isNonCriticalExc e
    | Just (_ :: NodeAttackedError) <- fromException e = True
    | Just DialogUnexpected{} <- fromException e = True
    | otherwise = False
```

you can write:

```haskell
isNonCriticalExc = \case
    Exc (_ :: NodeAttackedError) -> True  -- matching all exceptions of type 'NodeAttackedError'
    Exc DialogUnexpected{} -> True
    _ -> False
```

### PR DESCRIPTION
**Pull request by ChShersh**
Resolves #130 
Resolves #118 
Resolves #60 
Resolves #144

### CODE REVIEW

File: src/Universum/Container/Class.hs [hunk 1]
```diff
@@ -286,19 +167,62 @@ instance ToPairs (Map k v) where
...
+    {-# INLINE toList #-}
+
+    -- | Checks whether container is empty.
+    --
+    -- >>> null @Text ""
+    -- True
+    -- >>> null @Text "aba"
+    -- False
+    null :: t -> Bool
+    null = List.null . toList
```
Comment (vrom911) [inline src/Universum/Container/Class.hs]: I've noticed that there is `default` line for `toList`, but not for `null`

File: src/Universum/Container/Class.hs [hunk 2]
```diff
@@ -722,12 +671,6 @@ type family DisallowInstance (z :: Symbol) :: ErrorMessage where
...
 
-#define DISALLOW_TO_LIST_8(t, z) \
-    instance TypeError (DisallowInstance z) => \
-      ToList (t) where { \
-        toList = undefined; \
-        null = undefined; } \
-
 #define DISALLOW_CONTAINER_8(t, z) \
     instance TypeError (DisallowInstance z) => \
       Container (t) where { \
```
Comment (vrom911) [inline src/Universum/Container/Class.hs]: Probably, this can be simplified as there are default implementations for these functions

File: src/Universum/Container/Class.hs (hunk 1 above)
Comment (ChShersh) [reply src/Universum/Container/Class.hs]: Good point :+1: This can (and should) be done since `null` in `base` package is a member of `Foldable` type class

File: src/Universum/Container/Class.hs (hunk 2 above)
Comment (ChShersh) [reply src/Universum/Container/Class.hs]: I don't mind. We can make this scary CPP pragma much less scarier.
