### PR TITLE
[#100] Add bug

### LINKED ISSUE #100: Add bug=impureThrow
Define `bug` roughly as follows:

```
import Control.Exception.Safe (impureThrow)

data Bug = Bug SomeException CallStack

instance Exception Bug

bug :: (HasCallStack, Exception e) => e -> a
bug e = impureThrow $ Bug (toException e) ?callStack
```

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #100

### CODE REVIEW

File: src/Universum/Exception.hs [hunk 1]
```diff
@@ -19,6 +24,25 @@ import Control.Applicative (Applicative (pure))
...
+-- is not meant to be ever executed, but happens to be executed anyway.
+data Bug = Bug SomeException CallStack
+    deriving (Show)
+
+instance Exception Bug
+
+-- | Generate a pure value which, when forced, will synchronously
+-- throw the exception wrapped into 'Bug' data type.
+bug :: (HasCallStack, Exception e) => e -> a
+bug e = Safe.impureThrow (Bug (Safe.toException e) ?callStack)
```
Comment (int-index) [inline src/Universum/Exception.hs]: I found this note in `base` docs:

image

Instead of `?callStack`, we should use the `callStack` function from `GHC.Stack`.

File: src/Universum/Exception.hs [hunk 2]
```diff
@@ -19,6 +24,25 @@ import Control.Applicative (Applicative (pure))
...
+import GHC.Stack (CallStack, HasCallStack)
+
+import qualified Control.Exception.Safe as Safe (impureThrow, toException)
+
+-- | Type that represents exceptions used in cases when a particular codepath
+-- is not meant to be ever executed, but happens to be executed anyway.
+data Bug = Bug SomeException CallStack
+    deriving (Show)
+
+instance Exception Bug
```
Comment (int-index) [inline src/Universum/Exception.hs]: Let's have a proper `displayException` implementation here. We should use the `prettyCallStack` function from `GHC.Stack` to render the call stack, `displayException` to render the stored `SomeException`, and concatenate the two using with `"\n"` in between (`SomeException` comes first, then `"\n"`, then pretty-printed `CallStack`).

This would match the behavior of `error`.

File: src/Universum/Exception.hs (hunk 1 above)
Comment (int-index) [reply src/Universum/Exception.hs]: Then the `ImplicitParams` extension can be removed.
